import { Link } from "react-router-dom";
import { ArrowRight, BookOpen, GraduationCap, Inbox, MessageSquare, Sparkles } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import Avatar from "../components/Avatar";
import { SkillTag } from "../components/Badge";

export default function Dashboard() {
  const { user, profile, data } = useAuth();
  const teach = user.skills.filter((skill) => skill.type === "teach");
  const learn = user.skills.filter((skill) => skill.type === "learn");
  const received = data.requests.filter((request) => request.receiver_id === user.id);
  const connections = data.requests.filter((request) => request.status === "accepted" && (request.sender_id === user.id || request.receiver_id === user.id));
  const recommendations = data.users.filter((person) => person.id !== user.id && person.skills.some((skill) => skill.type === "teach" && learn.some((wanted) => wanted.name.toLowerCase() === skill.name.toLowerCase()))).slice(0, 4);
  const stats = [["Skills shared", teach.length, GraduationCap], ["Learning now", learn.length, BookOpen], ["Open requests", received.filter((request) => request.status === "pending").length, Inbox], ["Connections", connections.length, MessageSquare]];
  return <div className="space-y-10">
    <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 border-b border-[#e8e8e5] pb-8"><div><p className="text-xs uppercase tracking-[0.2em] font-semibold text-[#6b6b6b] mb-3">Workspace overview</p><h1 className="text-3xl md:text-5xl font-semibold tracking-[-0.055em] text-[#080808]">Good morning, {profile.full_name.split(" ")[0]}.</h1><p className="text-[#6b6b6b] mt-4">Continue learning or share something you know.</p></div><Link to="/profile" className="arrow-on-hover text-sm font-medium border-b border-[#080808] pb-1 w-fit">Complete your profile <ArrowRight size={14} className="inline ml-1" /></Link></header>
    <section className="grid grid-cols-2 lg:grid-cols-4 border-y border-[#e8e8e5]">{stats.map(([label, value, Icon]) => <div key={label} className="p-5 md:p-6 border-r border-b lg:border-b-0 border-[#e8e8e5] last:border-r-0"><div className="flex items-center justify-between mb-8"><span className="text-sm text-[#6b6b6b]">{label}</span><Icon size={18} className="text-[#6b6b6b]" /></div><p className="text-4xl font-semibold tracking-tight">{value}</p></div>)}</section>
    <section className="grid md:grid-cols-2 border-y border-[#080808]"><div className="p-6 md:p-8 md:border-r border-[#e8e8e5]"><div className="flex items-center gap-2 mb-6"><span className="w-2 h-2 rounded-full bg-[#c8ff3d]" /><h2 className="font-medium">Your skills</h2></div><div className="flex flex-wrap gap-2">{teach.length ? teach.map((skill) => <SkillTag key={skill.id} name={skill.name} type="teach" />) : <span className="text-sm text-[#6b6b6b]">Add something you can teach.</span>}</div></div><div className="p-6 md:p-8"><div className="flex items-center gap-2 mb-6"><span className="w-2 h-2 rounded-full bg-[#c8ff3d]" /><h2 className="font-medium">Learning</h2></div><div className="flex flex-wrap gap-2">{learn.length ? learn.map((skill) => <SkillTag key={skill.id} name={skill.name} type="learn" />) : <span className="text-sm text-[#6b6b6b]">Add something you want to learn.</span>}</div></div></section>
    <div className="grid lg:grid-cols-[1.2fr_.8fr] gap-12"><section><div className="flex items-center justify-between border-b border-[#080808] pb-4 mb-1"><h2 className="font-medium">Suggested connections</h2><Link to="/explore" className="arrow-on-hover text-sm text-[#6b6b6b] hover:text-black">Explore all <ArrowRight size={14} className="inline" /></Link></div>{recommendations.length ? <div>{recommendations.map((person) => <Link key={person.id} to={`/profile/${person.id}`} className="lift-on-hover flex items-center gap-4 py-5 border-b border-[#e8e8e5] group"><Avatar name={person.full_name} url={person.avatar_url} size={42} /><div className="flex-1 min-w-0"><div className="flex items-center justify-between gap-4"><p className="font-medium group-hover:underline">{person.full_name}</p><span className="text-[11px] uppercase tracking-[0.12em] text-[#6b6b6b]">Strong match</span></div><p className="text-sm text-[#6b6b6b] mt-1">{person.location}</p></div><SkillTag name={person.skills.find((skill) => skill.type === "teach" && learn.some((wanted) => wanted.name.toLowerCase() === skill.name.toLowerCase()))?.name} type="teach" /><ArrowRight size={16} className="text-[#999] group-hover:text-black" /></Link>)}</div> : <div className="py-10 text-sm text-[#6b6b6b]">Add learning skills to get personalized recommendations.</div>}</section><section><div className="border-b border-[#080808] pb-4 mb-1"><h2 className="font-medium">Recent activity</h2></div><div className="divide-y divide-[#e8e8e5]">{[["Pending requests", received.filter((request) => request.status === "pending").length, "/requests"], ["Accepted connections", connections.length, "/messages"], ["Skills on your profile", user.skills.length, "/profile"]].map(([label, value, href]) => <Link to={href} key={label} className="flex items-center justify-between py-5 group"><span className="text-sm text-[#6b6b6b]">{label}</span><span className="flex items-center gap-3 font-medium">{value}<ArrowRight size={15} className="text-[#999] group-hover:text-black" /></span></Link>)}</div><div className="mt-8 bg-[#f7f7f5] border border-[#e8e8e5] p-5"><Sparkles size={17} className="mb-7" /><p className="font-medium">Make one useful introduction today.</p><p className="text-sm text-[#6b6b6b] mt-2 leading-6">Explore the community and find someone whose skills complement yours.</p><Link to="/explore" className="arrow-on-hover inline-block mt-5 text-sm font-medium border-b border-black pb-1">Browse people <ArrowRight size={14} className="inline ml-1" /></Link></div></section></div>
  </div>;
}
