import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, MessageSquare, Search, Send } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import Avatar from "../components/Avatar";

export default function Messages() {
  const { userId } = useParams();
  const { user, data, sendMessage } = useAuth();
  const [search, setSearch] = useState("");
  const [text, setText] = useState("");
  const scrollRef = useRef(null);
  const ids = new Set(data.requests.filter((request) => request.status === "accepted" && (request.sender_id === user.id || request.receiver_id === user.id)).map((request) => request.sender_id === user.id ? request.receiver_id : request.sender_id));
  const connections = data.users.filter((person) => ids.has(person.id));
  const active = connections.find((person) => person.id === userId);
  const messages = data.messages.filter((message) => (message.sender_id === user.id && message.receiver_id === userId) || (message.sender_id === userId && message.receiver_id === user.id));
  useEffect(() => { if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; }, [messages.length]);
  const submit = (event) => { event.preventDefault(); if (text.trim() && active) { sendMessage(active.id, text.trim()); setText(""); } };
  if (!connections.length) return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-gray-900">Messages</h1><p className="text-gray-500 mt-1">Chat with people you&apos;ve connected with.</p></div><div className="bg-white rounded-xl border border-gray-200 p-10 text-center"><MessageSquare size={32} className="mx-auto text-gray-300 mb-3" /><p className="text-gray-500">No conversations yet. Accept a request to start messaging.</p><Link to="/explore" className="inline-block mt-3 text-sm text-brand-700">Explore skills</Link></div></div>;
  return <div className="space-y-4"><div><h1 className="text-2xl font-bold text-gray-900">Messages</h1><p className="text-gray-500 mt-1">Chat with people you&apos;ve connected with.</p></div><div className="bg-white rounded-2xl border border-gray-200 flex h-[600px] overflow-hidden"><div className={`w-full md:w-72 border-r border-gray-200 flex flex-col ${userId ? "hidden md:flex" : "flex"}`}><div className="p-3 border-b"><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search conversations" className="w-full pl-9 pr-3 py-2 text-sm border rounded-lg" /></div></div><div className="flex-1 overflow-y-auto">{connections.filter((person) => person.full_name.toLowerCase().includes(search.toLowerCase())).map((person) => <Link key={person.id} to={`/messages/${person.id}`} className={`flex items-center gap-3 p-3 border-b border-gray-50 ${userId === person.id ? "bg-brand-50" : "hover:bg-gray-50"}`}><Avatar name={person.full_name} url={person.avatar_url} size={40} /><div><p className="text-sm font-medium">{person.full_name}</p><p className="text-xs text-gray-500">{person.location}</p></div></Link>)}</div></div>{active ? <div className="flex-1 flex flex-col"><div className="p-4 border-b flex items-center gap-3"><Link to="/messages" className="md:hidden"><ArrowLeft size={20} /></Link><Avatar name={active.full_name} url={active.avatar_url} size={36} /><div><p className="font-medium">{active.full_name}</p><Link to={`/profile/${active.id}`} className="text-xs text-brand-700">View profile</Link></div></div><div ref={scrollRef} className="flex-1 overflow-y-auto p-4 space-y-3 bg-gray-50">{messages.length ? messages.map((message) => <div key={message.id} className={`flex ${message.sender_id === user.id ? "justify-end" : "justify-start"}`}><div className={`max-w-[75%] px-3 py-2 rounded-2xl text-sm ${message.sender_id === user.id ? "bg-brand-600 text-white" : "bg-white border text-gray-700"}`}>{message.content}</div></div>) : <p className="text-center text-sm text-gray-400 mt-10">Start the conversation.</p>}</div><form onSubmit={submit} className="p-3 border-t flex gap-2"><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Write a message..." className="flex-1 border rounded-lg px-3 py-2 text-sm" /><button className="p-2.5 bg-brand-600 text-white rounded-lg" aria-label="Send message"><Send size={17} /></button></form></div> : <div className="hidden md:flex flex-1 items-center justify-center text-gray-400 text-sm">Select a connection to message.</div>}</div></div>;
}
